REST Modding Example
StrangeLoopGames/EcoModKit pull request #51
Opened 2022-05-31 20:23 UTC by JulianMa

This is a basic working example for an extension of the Eco WebServer Rest API.
This will be possible in a future Version of Eco.

2022-05-31 21:04 UTC, JulianMa commented
I added the README. 
It should be notes, that this feature will only be available, after it is Supported by the EcoServer:
https://github.com/StrangeLoopGames/Eco/pull/10888

2022-06-01 04:18 UTC, thetestgame approved these changes

2022-06-04 14:21 UTC, redwyre requested changes

2022-06-04 14:21 UTC, redwyre commented on Examples/ExtendRestApi/Server/HelloWorldController.cs
> +        public String getAll()
Should just be called `Get()`

2022-06-04 14:21 UTC, redwyre commented on Examples/ExtendRestApi/Server/HelloWorldController.cs
> +namespace Eco.WebServer.Web.Controllers
Don't use the Eco namespace, use your mods namespace. This makes it hard to tell if errors are coming from Eco or mods.

2022-06-04 15:17 UTC, JulianMa commented on Examples/ExtendRestApi/Server/HelloWorldController.cs
> +namespace Eco.WebServer.Web.Controllers
I fixed both.

2022-06-04 15:22 UTC, redwyre approved these changes

2022-06-25 18:59 UTC, merged