Added Corn On The Cob Food Mod Example
StrangeLoopGames/EcoModKit pull request #55
Opened 2022-07-08 07:49 UTC by Kolark

Added Corn On The Cob Food Mod Example and also a guide on how it was made. (See CornOnTheCob/README)

2022-07-08 16:50 UTC, redwyre requested changes

2022-07-08 16:50 UTC, redwyre commented on Examples/CornOnTheCob/README.md
> +Link: https://drive.google.com/drive/folders/1C6OhXv_PF4cdqDDSVGV9ROIHz_pbbPK_?usp=sharing
This should be copied to the wiki under https://wiki.play.eco/en/Mod_Development

2022-07-08 16:50 UTC, redwyre commented on Examples/CornOnTheCob/README.md
> +Link: https://drive.google.com/drive/folders/1coxU8BGCyjKS52eOphCIMWX7ULiCEgac?usp=sharing
is this the result of building this mod as is, or includes other assets?

2022-07-15 17:17 UTC, redwyre requested changes

2022-07-15 17:17 UTC, redwyre commented on Examples/CornOnTheCob/README.md
> +### Server side file + resulting bundle after building example modkit can be found [HERE](https://drive.google.com/drive/folders/1coxU8BGCyjKS52eOphCIMWX7ULiCEgac?usp=sharing)
you can remove this, it's going to go out of date pretty fast. We'll try to build and release these mods eventually so that will take care of it.

Also add a short description of the mod here

2022-07-26 04:50 UTC, redwyre approved these changes

2022-07-26 04:50 UTC, redwyre commented on Examples/CornOnTheCob/Client/Assets/CornOnTheCob/HandAnimations/.gitignore
> +!*.meta
why do you need this? meta files shouldn't be ignored

2022-07-26 05:26 UTC, Kolark commented on Examples/CornOnTheCob/Client/Assets/CornOnTheCob/HandAnimations/.gitignore
> +!*.meta
the Modkit .gitignore ignores all meta files, so I made an exception for the folder containing the animations so that the Custom Animset wouldn't lose its references.
Now that I think about it I should move it to the root of the CornOnTheCob example so that all meta files on the Corn on the cob project are added.

2022-07-26 16:51 UTC, thetestgame approved these changes

2022-08-27 08:22 UTC, merged